### ISSUE TITLE
Anchor scrolling offset.

### ISSUE THREAD

**Issue by omniraptorr** [tts-community/Tabletop-Simulator-API#20]
So, the issue is that i want to be able to scroll to a specific row in a markdown table. trouble is, the both the table and the fixed site header are variable height, so lining them up is tricky. if some css wizard could take a look at the theme i would be very grateful.

at the moment, theme.css has the following declaration:
``` css
.anchor {
   content:"";
   display:block;
   padding-top: 72px;
   margin:-72px 0 0; /* negative fixed header height */
   pointer-events: none;
}
```
relevant links:
https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-padding-top - broken on safari and didn't work when i tried setting it in firefox, but i may have gotten something wrong
https://stackoverflow.com/questions/10732690/offsetting-an-html-anchor-to-adjust-for-fixed-header - relevant question, but we have the added problem of being inside a variable width table.

p.s. also not sure if this issue should be against our repo or against mkdocs. it seems like it's not inherent to our theme/repo.
